### ISSUE TITLE
weights files?

### ISSUE THREAD

**Issue by kenpchess** [tadeasf/python_chess_gui#1]
Did you post the weights files (pb.gz) somewhere? Thanks in advance!

**Comment by tadeasf** [comment]
https://github.com/CSSLab/maia-chess/tree/master/maia_weights

**Comment by tadeasf** [comment]
keep in mind is a project i've writtten in a few hours, so, it's not hyper polished (e.g. for some reason the a1 square is not available through mouse clicks so you gotta use the manual bar to type it out) but it works well when you want to try out maia and other engines

**Comment by tadeasf** [comment]
> Did you post the weights files (pb.gz) somewhere? Thanks in advance!
https://github.com/CSSLab/maia-chess/tree/master/maia_weights

**Comment by tadeasf** [comment]
i'm gonna close this, okay? if you'd need anything else open another issue
